import webbrowser
import subprocess
import shutil
import re

def website(url):
    # Determine if Chrome is available
    chrome_path = shutil.which("chrome") or shutil.which("google-chrome")
    if chrome_path:
        subprocess.run([chrome_path, url])
    else:
        webbrowser.open(url)
   # Predefined web map
web_map = {
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "facebook": "https://www.facebook.com",
    "twitter": "https://twitter.com",
    "instagram": "https://www.instagram.com",
    "reddit": "https://www.reddit.com",
    "linkedin": "https://www.linkedin.com",
    "amazon": "https://www.amazon.com",
    "ebay": "https://www.ebay.com",
    "wikipedia": "https://www.wikipedia.org",
    "stackoverflow": "https://stackoverflow.com",
    "github": "https://github.com",
    "yahoo": "https://www.yahoo.com",
    "bing": "https://www.bing.com",
    "pinterest": "https://www.pinterest.com",
    "netflix": "https://www.netflix.com",
    "spotify": "https://www.spotify.com",
    "apple": "https://www.apple.com",
    "microsoft": "https://www.microsoft.com",
    "walmart": "https://www.walmart.com",
    "target": "https://www.target.com",
    "hulu": "https://www.hulu.com",
    "craigslist": "https://www.craigslist.org",
    "imdb": "https://www.imdb.com",
    "nytimes": "https://www.nytimes.com",
    "bbc": "https://www.bbc.co.uk",
    "cnn": "https://www.cnn.com",
    "forbes": "https://www.forbes.com",
    "weather": "https://www.weather.com",
    "reddit": "https://www.reddit.com",
    "Adobe Premiere Pro Forums": "https://community.adobe.com/t5/premiere-pro/bd-p/premiere-pro?page=1&sort=latest_replies&filter=all",
    "Final Cut Pro Forums": "https://discussions.apple.com/community/professional_applications/final_cut_pro_x",
    "Avid Media Composer Forums": "https://community.avid.com/forums/default.aspx",
    "DaVinci Resolve Forums": "https://forum.blackmagicdesign.com/viewforum.php?f=21",
    "VideoCopilot (After Effects Tutorials)": "https://www.videocopilot.net",
    "Red Giant (Video Editing Plugins)": "https://www.redgiant.com",
    "B&H Photo Video (Video Equipment)": "https://www.bhphotovideo.com",
    "Sports Illustrated": "https://www.si.com",
    "ESPN": "https://www.espn.com",
    "NBA": "https://www.nba.com",
    "NFL": "https://www.nfl.com",
    "MLB": "https://www.mlb.com",
    "NHL": "https://www.nhl.com",
    "FIFA": "https://www.fifa.com",
    "UFC": "https://www.ufc.com",
    "PGA Tour": "https://www.pgatour.com",
    "Olympics": "https://olympics.com",
    "Tennis.com": "https://www.tennis.com",
    "Runner's World": "https://www.runnersworld.com",
    "Cyclingnews": "https://www.cyclingnews.com",
    "Golf Digest": "https://www.golfdigest.com",
    "Bleacher Report": "https://bleacherreport.com",
    "CBS Sports": "https://www.cbssports.com",
    "NBC Sports": "https://www.nbcsports.com",
    "FOX Sports": "https://www.foxsports.com",
    "BBC Sport": "https://www.bbc.co.uk/sport",
    "ESPNcricinfo": "https://www.espncricinfo.com",
    "Sportsnet": "https://www.sportsnet.ca",
    "The Athletic": "https://theathletic.com",
    "World Surf League": "https://www.worldsurfleague.com",
    "Formula 1": "https://www.formula1.com",
    "MotoGP": "https://www.motogp.com",
    "Red Bull Racing": "https://www.redbull.com/int-en/team/red-bull-racing",
    "WWE": "https://www.wwe.com",
    "NASCAR": "https://www.nascar.com",
    "Athletics Weekly": "https://www.athleticsweekly.com",
    "GitHub": "https://github.com",
    "Stack Overflow": "https://stackoverflow.com",
    "Medium (Programming)": "https://medium.com/topic/programming",
    "Dev.to": "https://dev.to",
    "Hacker News": "https://news.ycombinator.com",
    "Codecademy": "https://www.codecademy.com",
    "GeeksforGeeks": "https://www.geeksforgeeks.org",
    "LeetCode": "https://leetcode.com",
    "Hackerrank": "https://www.hackerrank.com",
    "FreeCodeCamp": "https://www.freecodecamp.org",
    "Mozilla Developer Network (MDN)": "https://developer.mozilla.org",
    "W3Schools": "https://www.w3schools.com",
    "The New Boston (Tutorials)": "https://thenewboston.com",
    "CodePen": "https://codepen.io",
    "The Odin Project": "https://www.theodinproject.com",
    "Coursera (Computer Science)": "https://www.coursera.org/browse/computer-science",
    "Udemy (Programming Courses)": "https://www.udemy.com/courses/development/",
    "Pluralsight": "https://www.pluralsight.com",
    "Code.org": "https://code.org",
    "Kaggle": "https://www.kaggle.com",
    "CodeProject": "https://www.codeproject.com",
    "CodersRank": "https://profile.codersrank.io",
    "Topcoder": "https://www.topcoder.com",
    "The Code Player": "https://thecodeplayer.com",
    "CSS-Tricks": "https://css-tricks.com",
    "DZone": "https://dzone.com",
    "Programiz": "https://www.programiz.com",
    "Tuts+": "https://tutsplus.com",
    "Reddit Programming": "https://www.reddit.com/r/programming",
    "CodeNewbie": "https://www.codenewbie.org",
    "Google Classroom": "https://classroom.google.com",
    "Khan Academy": "https://www.khanacademy.org",
    "EdX": "https://www.edx.org",
    "Coursera": "https://www.coursera.org",
    "Quizlet": "https://quizlet.com",
    "Scholastic": "https://www.scholastic.com",
    "TED-Ed": "https://ed.ted.com",
    "PBS LearningMedia": "https://www.pbslearningmedia.org",
    "Teachers Pay Teachers": "https://www.teacherspayteachers.com",
    "BBC Bitesize": "https://www.bbc.co.uk/bitesize",
    "National Geographic Kids": "https://kids.nationalgeographic.com",
    "Duolingo": "https://www.duolingo.com",
    "HippoCampus": "https://www.hippocampus.org",
    "IXL": "https://www.ixl.com",
    "Study.com": "https://www.study.com",
    "Mathway": "https://www.mathway.com",
    "SparkNotes": "https://www.sparknotes.com",
    "CliffsNotes": "https://www.cliffsnotes.com",
    "Math Playground": "https://www.mathplayground.com",
    "Reading Eggs": "https://readingeggs.com",
    "Cool Math": "https://www.coolmath.com",
    "Grammarly": "https://www.grammarly.com",
    "History.com": "https://www.history.com",
    "ReadWriteThink": "https://www.readwritethink.org",
    "Smithsonian Education": "https://www.smithsonianeducation.org",
    "NASA Kids' Club": "https://www.nasa.gov/kidsclub",
    "Discovery Education": "https://www.discoveryeducation.com",
    "IXL Learning": "https://www.ixl.com",
    "Mathletics": "https://www.mathletics.com",
    "Brainscape": "https://www.brainscape.com",
    "Netflix": "https://www.netflix.com",
    "Hulu": "https://www.hulu.com",
    "Disney+": "https://www.disneyplus.com",
    "Amazon Prime Video": "https://www.amazon.com/Prime-Video",
    "HBO Max": "https://www.hbomax.com",
    "YouTube": "https://www.youtube.com",
    "Twitch": "https://www.twitch.tv",
    "Reddit": "https://www.reddit.com",
    "IMDb": "https://www.imdb.com",
    "Rotten Tomatoes": "https://www.rottentomatoes.com",
    "Spotify": "https://www.spotify.com",
    "Apple Music": "https://music.apple.com",
    "SoundCloud": "https://soundcloud.com",
    "Pandora": "https://www.pandora.com",
    "Last.fm": "https://www.last.fm",
    "Tidal": "https://tidal.com",
    "Deezer": "https://www.deezer.com",
    "Google Play Music": "https://play.google.com/music",
    "Audible": "https://www.audible.com",
    "Goodreads": "https://www.goodreads.com",
    "Wattpad": "https://www.wattpad.com",
    "Kindle Store": "https://www.amazon.com/Kindle-eBooks",
    "Etsy": "https://www.etsy.com",
    "Pinterest": "https://www.pinterest.com",
    "Instagram": "https://www.instagram.com",
    "Snapchat": "https://www.snapchat.com",
    "TikTok": "https://www.tiktok.com",
    "Twitter": "https://twitter.com",
    "Facebook": "https://www.facebook.com",
    "Vimeo": "https://vimeo.com",
    "Microsoft": "https://www.microsoft.com",
    "Microsoft Store": "https://www.microsoft.com/en-us/store/b/home",
    "Microsoft 365": "https://www.microsoft.com/en-us/microsoft-365",
    "Microsoft Office": "https://www.microsoft.com/en-us/microsoft-365/get-started-with-office-2019",
    "Windows": "https://www.microsoft.com/en-us/windows",
    "Windows Update": "https://support.microsoft.com/en-us/help/12373/windows-update-faq",
    "Microsoft Edge": "https://www.microsoft.com/en-us/edge",
    "Visual Studio": "https://visualstudio.microsoft.com",
    "Azure": "https://azure.microsoft.com",
    "Xbox": "https://www.xbox.com",
    "Xbox Game Pass": "https://www.xbox.com/en-US/xbox-game-pass",
    "Microsoft Developer Network (MSDN)": "https://developer.microsoft.com/en-us",
    "GitHub (owned by Microsoft)": "https://github.com",
    "Microsoft Tech Community": "https://techcommunity.microsoft.com",
    "Microsoft News": "https://news.microsoft.com",
    "Microsoft Support": "https://support.microsoft.com",
    "Microsoft Research": "https://www.microsoft.com/en-us/research",
    "Microsoft Learn": "https://learn.microsoft.com",
    "Microsoft Teams": "https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software",
    "Bing": "https://www.bing.com",
    "Microsoft OneDrive": "https://www.microsoft.com/en-us/microsoft-365/onedrive/online-cloud-storage",
    "Microsoft Power BI": "https://powerbi.microsoft.com",
    "Microsoft Dynamics 365": "https://dynamics.microsoft.com",
    "Microsoft News Center": "https://news.microsoft.com",
    "Microsoft Security Intelligence": "https://www.microsoft.com/security/blog",
    "Microsoft Investor Relations": "https://www.microsoft.com/en-us/investor",
    "Microsoft Accessibility": "https://www.microsoft.com/en-us/accessibility",
    "Microsoft Garage": "https://www.microsoft.com/en-us/garage",
    "Microsoft AI": "https://www.microsoft.com/en-us/ai",
    'apple': 'https://www.apple.com',
    'microsoft': 'https://www.microsoft.com',
    'yahoo': 'https://www.yahoo.com',
    'bing': 'https://www.bing.com',
    'paypal': 'https://www.paypal.com',
    'ebay': 'https://www.ebay.com',
    'walmart': 'https://www.walmart.com',
    'target': 'https://www.target.com',
    'craigslist': 'https://www.craigslist.org',
    'pinterest': 'https://www.pinterest.com',
    'hulu': 'https://www.hulu.com',
    'pandora': 'https://www.pandora.com',
    'wordpress': 'https://www.wordpress.org',
    'quora': 'https://www.quora.com',
    'espn': 'https://www.espn.com',
    'nba': 'https://www.nba.com',
    'nfl': 'https://www.nfl.com',
    'mlb': 'https://www.mlb.com',
    'nationalgeographic': 'https://www.nationalgeographic.com',
    'weather': 'https://www.weather.com',
    'tripadvisor': 'https://www.tripadvisor.com',
    'yelp': 'https://www.yelp.com',
    'imdb': 'https://www.imdb.com',
    'buzzfeed': 'https://www.buzzfeed.com',
    'forbes': 'https://www.forbes.com',
    'cnbc': 'https://www.cnbc.com',
    'businessinsider': 'https://www.businessinsider.com',
    'nasa': 'https://www.nasa.gov',
    'ted': 'https://www.ted.com',
    'spotify': 'https://www.spotify.com',
    'hackernews': 'https://news.ycombinator.com',
    'dribbble': 'https://www.dribbble.com',
    'behance': 'https://www.behance.net',
    'adobe': 'https://www.adobe.com',
    'ubuntu': 'https://www.ubuntu.com',
    'docker': 'https://www.docker.com',
    'raspberrypi': 'https://www.raspberrypi.org',
    'arstechnica': 'https://arstechnica.com',
    'techcrunch': 'https://techcrunch.com',
    'cnet': 'https://www.cnet.com',
    'engadget': 'https://www.engadget.com',
    'gizmodo': 'https://gizmodo.com',
    'lifehacker': 'https://lifehacker.com',
    'webmd': 'https://www.webmd.com',
    'mayoclinic': 'https://www.mayoclinic.org',
    'nih': 'https://www.nih.gov',
    'harvard': 'https://www.harvard.edu',
    'mit': 'https://web.mit.edu',
    'stanford': 'https://www.stanford.edu',
    'coursera': 'https://www.coursera.org',
    'udacity': 'https://www.udacity.com',
    'edx': 'https://www.edx.org',
    'khanacademy': 'https://www.khanacademy.org',
    'codecademy': 'https://www.codecademy.com',
    'stackoverflow': 'https://stackoverflow.com',
    'gitlab': 'https://www.gitlab.com',
    'bitbucket': 'https://bitbucket.org',
    'digg': 'https://digg.com',
    'slashdot': 'https://slashdot.org',
    'medium': 'https://medium.com',
    'mashable': 'https://mashable.com',
    'wired': 'https://www.wired.com',
    'bbcnews': 'https://www.bbc.co.uk/news',
    'aljazeera': 'https://www.aljazeera.com',
    'reuters': 'https://www.reuters.com',
    'npr': 'https://www.npr.org',
    'nytimes': 'https://www.nytimes.com',
    'washingtonpost': 'https://www.washingtonpost.com',
    'theguardian': 'https://www.theguardian.com',
    'latimes': 'https://www.latimes.com',
    'usatoday': 'https://www.usatoday.com',
    'time': 'https://time.com',
    'facebook': 'https://www.facebook.com',
    'twitter': 'https://www.twitter.com',
    'instagram': 'https://www.instagram.com',
    'linkedin': 'https://www.linkedin.com',
    'tumblr': 'https://www.tumblr.com',
    'snapchat': 'https://www.snapchat.com',
    'whatsapp': 'https://www.whatsapp.com',
    'telegram': 'https://telegram.org',
    'youtube': 'https://www.youtube.com',
    'vimeo': 'https://vimeo.com',
    'twitch': 'https://www.twitch.tv',
    'soundcloud': 'https://soundcloud.com',
    'myspace': 'https://myspace.com',
    'flickr': 'https://www.flickr.com',
    'vine': 'https://vine.co',
    'periscope': 'https://www.pscp.tv',
    'mix': 'https://mix.com',
    'meetup': 'https://www.meetup.com',
    'badoo': 'https://badoo.com',
    'okcupid': 'https://www.okcupid.com',
    'tinder': 'https://tinder.com',
    'grindr': 'https://www.grindr.com',
    'hinge': 'https://hinge.co',
    'tagged': 'https://www.tagged.com',
    'hi5': 'https://hi5.com',
    'skout': 'https://www.skout.com',
    'friendster': 'https://www.friendster.com',
    'orcutt': 'https://orcutt.com',
    'xanga': 'https://www.xanga.com',
    'bebo': 'https://bebo.com',
    'plaxo': 'https://www.plaxo.com',
    'sonico': 'https://www.sonico.com',
    'moco': 'https://www.mocospace.com',
    'blued': 'https://www.blued.com',
    'weibo': 'https://www.weibo.com',
    'qq': 'https://www.qq.com',
    'douban': 'https://www.douban.com',
    'cyworld': 'https://www.cyworld.com',
    'mixi': 'https://mixi.jp',
    'renren': 'https://www.renren.com',
    'hyves': 'https://hyves.nl',
    'foursquare': 'https://foursquare.com',
    'swarm': 'https://www.swarmapp.com',
    'untappd': 'https://untappd.com',
    'goodreads': 'https://www.goodreads.com',
    'lastfm': 'https://www.last.fm',
    'delicious': 'https://del.icio.us',
    'stumbleupon': 'https://www.stumbleupon.com',
    'diigo': 'https://www.diigo.com',
    'newsvine': 'https://www.newsvine.com',
    'folkd': 'https://www.folkd.com',
    'scoop.it': 'https://www.scoop.it',
    'pearltrees': 'https://www.pearltrees.com',
    'dzone': 'https://dzone.com',
    'reddit': 'https://www.reddit.com',
    'hubpages': 'https://hubpages.com',
    'livejournal': 'https://www.livejournal.com',
    'bloglovin': 'https://www.bloglovin.com',
    'blogger': 'https://www.blogger.com',
    'taringa': 'https://www.taringa.net',
    'skyrock': 'https://www.skyrock.com',
    'twoo': 'https://www.twoo.com',
    'viadeo': 'https://www.viadeo.com',
    'diaspora': 'https://diasporafoundation.org',
    'ello': 'https://ello.co',
    'mastodon': 'https://joinmastodon.org',
    'meowchat': 'https://www.meowchat.com',
    'google': 'https://www.google.com',
    'w3schools': 'https://www.w3schools.com',
    'canva': 'https://www.canva.com',
    'youtubestudio': 'https://studio.youtube.com',
    'github': 'https://www.github.com',
    'udemy': 'https://www.udemy.com',
    'hackerrank': 'https://www.hackerrank.com',
    'codepen': 'https://codepen.io',
    'slack': 'https://slack.com',
    'zoom': 'https://zoom.us',
    'amazon': 'https://www.amazon.com',
    'netflix': 'https://www.netflix.com',
    'stackexchange': 'https://stackexchange.com',
    'cnn': 'https://www.cnn.com',
    'ubereats': 'https://www.ubereats.com',
    'doordash': 'https://www.doordash.com',
    'postmates': 'https://www.postmates.com',
    'grubhub': 'https://www.grubhub.com',
    'instacart': 'https://www.instacart.com',
    'booking': 'https://www.booking.com',
    'expedia': 'https://www.expedia.com',
    'airbnb': 'https://www.airbnb.com',
    'zillow': 'https://www.zillow.com',
    'realtor': 'https://www.realtor.com',
    'cars': 'https://www.cars.com',
    'autotrader': 'https://www.autotrader.com',
    'edmunds': 'https://www.edmunds.com',
    'kelleybluebook': 'https://www.kbb.com',
    'carmax': 'https://www.carmax.com',
    'chatgpt': 'https://chat.openai.com/'

}
    
def find_query(url):
    # Remove common extensions and protocols
    filtered_name = re.sub(r'(https?://|www\.|\.com|\.in|\.xyz)', '', url)
    
 
    
    if filtered_name in web_map:
        return {"url": web_map[filtered_name], "name": filtered_name}
    else:
        # If not found, create a URL with https and .com
        return {"url": f"https://{filtered_name}.com", "name": filtered_name}

def open_website(arguments):
    url = arguments.get("url")
    if not url:
        return {"response": "Please specify a URL to open."}
    
    query_result = find_query(url)
    website(query_result["url"])
    return {"response": f"Opening {query_result['name']} in browser."}

if __name__=="__main__":
    # Examples of using the functions
    print(open_website({"url": "wekipedia"}))  # Should open Google and print "Opening google in browser."
    print(open_website({"url": "github"})) # Should open Python and print "Opening python in browser."
    # print(open_website({"url": "unknownsite.com"})) # Should create a URL "https://unknownsite.com" and open it.
