
ofline_dlg =[
  "I'm currently offline, operating with limited capabilities.",
  "Sorry, I'm offline at the moment. My responses may be delayed.",
  "I'm offline right now. I'll do my best with limited functionality.",
  "Currently offline. Responses may be slower than usual.",
  "My apologies, I'm offline and may respond slowly.",
  "I'm offline temporarily, so my capabilities are limited.",
  "Offline mode activated. I'll try my best to assist you.",
  "Sorry, I'm offline and might be a bit slower in responding.",
  "Currently offline. Expect slower responses than usual.",
  "I'm offline right now, so responses may be delayed.",
  "Offline mode engaged. I'll provide assistance as best I can.",
  "Apologies, I'm offline temporarily and may respond slowly.",
  "I'm currently offline. Responses may be delayed due to limited access.",
  "Sorry, I'm in offline mode. I'll still do my best to help you.",
  "Offline status: I'll respond as quickly as I can given the circumstances.",
  "Currently operating offline. Responses may be delayed.",
  "I'm offline for now, so I might not respond immediately.",
  "Offline mode: Expect some delay in my responses.",
  "Sorry, I'm offline at the moment. I appreciate your patience.",
  "Offline temporarily. I'll assist you to the best of my current capabilities."
]
low_b = [
"It appears your device is running low on battery. Would you like assistance in finding a charging solution?",
"Sir, I've noticed a decrease in power levels. Shall I initiate a charging protocol for your device?",
" I recommend connecting your device to a power source to ensure uninterrupted functionality.",
"Sir, the energy levels are depleting. May I suggest plugging in your device for a power boost?",
" Power reserves are diminishing. Would you prefer I locate a charging station for you?",
"Sir, the battery is critically low. Would you like guidance on charging options available?",
" It seems the power is dwindling. Shall I assist you in finding a charging solution?",
"Sir, the battery indicator is signaling a low charge. May I guide you to a charging point?",
". Your device is in need of a power source. Would you like help in securing one?",
"Sir, I've detected a decrease in battery levels. Shall I guide you to the nearest charging point?",
" Power levels are dropping. Would you prefer I locate a charging station for your device?",
"It's advisable to charge your device now to avoid any disruptions. May I assist you in finding a charging point?",
]
last_low = [
"Sir, this is your final warning. The battery is critically low. Shall I assist you in finding a charging solution?",
"Urgent message: your device is running on very low battery. Would you like guidance on charging options?",
"Your device is on its last bit of power. May I suggest connecting it to a charger immediately?",
"Sir, immediate action is required. The battery is dangerously low. Would you like assistance in locating a charging point?",
"This is a critical alert. Your device is about to power off due to low battery. How may I assist you?",
"Sir, the battery is at a critical level. Urgently connect your device to a power source to prevent shutdown.",
"It's crucial. Your device is running out of power fast. Shall I guide you to the nearest charging station?",
"Sir, the battery is dangerously low. Immediate charging is recommended to avoid any disruptions. How may I assist you?",
"Your device is in a critical state. Would you like help in finding a charging solution urgently?",
"Sir, low battery alert. Urgent action needed. Shall I assist you in locating a charging point?",
"The battery is extremely low. Connecting to a power source is highly recommended at this moment.",
"Hello, sir. Critical battery situation. Immediate charging is advised. May I guide you to a suitable power source?",
"Sir, your device is on its last legs. Urgent charging is required. Would you like help in finding a charging point?",
" The battery is dangerously low. Shall I assist you in securing a power source?",
"Sir, this is an emergency. Your device is running critically low on battery. May I guide you to charge it promptly?",
"Immediate attention needed. The battery is very low. How may I assist you in finding a charging solution?",
"Sir, urgent notice. The battery is at a critical level. Connecting to a charger is highly recommended.",
"Greetings, sir. This is a final warning. Your device is about to power off due to low battery. How would you like to proceed?",
"Sir, the battery is dangerously low. Immediate charging is essential. Shall I guide you to a suitable power source?",
" Urgent alert: low battery. May I assist you in finding a charging solution before your device powers off?",
]
full_battery =[
"Sir, the battery is at 100 percent capacity. It seems fully charged. Would you like to unplug it?",
" Battery status: 100 percent. It appears fully charged. Shall I recommend unplugging it?",
"sir. Battery power is at its peak, 100 percent. Would you prefer to unplug your device now?",
"Sir, the battery level is showing 100 percent, indicating a full charge. Should I suggest unplugging it?",
"Battery status is 100 percent, indicating a full charge. Would you like to unplug your device?",
"Sir, your device is at 100 percent battery. It seems fully charged. May I suggest unplugging it for efficiency?",
" Battery power is at its maximum, 100 percent. Would you prefer to unplug your device at this point?",
"Sir, the battery is fully charged at 100 percent. Shall I recommend unplugging it to conserve energy?",
". Your device is showing 100 percent battery, indicating a full charge. Would you like to unplug it now?",
"Sir, the battery status is 100 percent, signifying a full charge. May I suggest unplugging it for optimal usage?",
". Battery power is at its peak, 100 percent. Would you prefer to unplug your device for efficiency?",
" Battery level is showing 100 percent, indicating a full charge. Shall I recommend unplugging it?",
"Sir, your device is fully charged at 100 percent. Would you like assistance in unplugging it for optimal use?",
"sir. Battery status is 100 percent, indicating a full charge. Shall I guide you in unplugging your device?",
"Sir, the battery is fully charged at 100 percent. May I suggest unplugging it to conserve energy?",
"Battery power is at its maximum, 100 percent. Would you like to unplug your device now?",
"Battery level is showing 100 percent, signifying a full charge. Shall I recommend unplugging it?",
"Sir, your device is at 100 percent battery. It seems fully charged. Would you like assistance in unplugging it?",
" Battery status is 100 percent, indicating a full charge. May I suggest unplugging it for optimal usage?",
"Sir, the battery is fully charged at 100 percent. Shall I guide you in unplugging it to conserve energy?",
]
plug_in = [
"Sir, plugging successful. Your device is now charging efficiently.",
" The device is now plugged in, and the charging process has started.",
"sir. Plugging accomplished. Your device is currently charging.",
"Sir, the connection is established. Your device is now charging successfully.",
"Plugging completed. Your device is charging as expected.",
"Sir, the cable is connected. Your device is now charging smoothly.",
"Plugging confirmed. Your device has initiated the charging process.",
"Sir, the device is securely plugged in. It's now charging.",
" Plugging executed. Your device is actively charging now.",
"Sir, connection successful. Your device is in the process of charging.",
" Plugging accomplished. Your device is now charging efficiently.",
" The charging process has commenced. Your device is now plugged in.",
"Sir, plugging confirmed. Your device is successfully charging now.",
" Connection established. Your device is currently charging.",
"Sir, plugging successful. Your device has started charging as intended.",
" The cable is securely connected. Your device is now charging.",
"Plugging completed. Your device is actively charging now.",
"Sir, the charging process has started. Plugging successful.",
" Your device is now charging, as the plugging process was successful.",
"Sir, the cable is connected. Your device is successfully charging as expected.",
]
plug_out =[
" Your device has been unplugged. You are now running on battery power.",
" The connection has been removed. You are currently operating on battery power.",
"Sir, the device has been unplugged. You are now relying on your battery for power.",
" Your device has been disconnected. You are currently running on battery power.",
"The cable has been removed. You are now operating on your battery's power.",
"Sir, the connection has been detached. You are currently running on your device's battery.",
" Your device is unplugged. You are now relying on battery power.",
"Sir, the cable has been disconnected. You are currently operating on your device's battery.",
" Your device has been unplugged. You are now running on battery power.",
" The connection has been removed. You are currently operating on your battery.",
"Sir, your device is unplugged. You are now running on battery power.",
" The cable has been removed. You are currently relying on your battery.",
"Sir, your device has been unplugged. You are now running on battery power.",
" The connection has been detached. You are currently relying on your battery.",
"Your device is unplugged. You are now operating on battery power.",
"Sir, the cable has been disconnected. You are currently running on your device's battery.",
"Your device has been unplugged. You are now relying on battery power.",
"Sir, the connection has been removed. You are currently operating on your battery.",
"sir. Your device is unplugged. You are now running on battery power.",
" The cable has been removed. You are currently operating on your device's battery.",
]
search_result = [
"Sir, this is the search result for your question or query.",
" Here is the information based on your question or inquiry.",
"The search results for your question or query are as follows.",
"Sir, I have found the following information related to your question or query.",
"Here are the search results in response to your question or inquiry.",
"Sir, the search outcome for your question or query is presented here.",
"This is what I found in response to your question or inquiry.",
"Sir, here are the search results pertaining to your question or query.",
"The information based on your question or inquiry is as follows.",
"Sir, this is the outcome of the search for your question or query.",
]
yt_search = [
"Sir, searching your query on YouTube now for relevant content.",
"I'll initiate a YouTube search based on your query.",
"Let me find your query on YouTube for you.",
"Sir, I'm searching your inquiry on YouTube for related videos.",
"Initiating a YouTube search for your specific query.",
"Sir, I'll search YouTube for content related to your inquiry.",
"Let me find relevant videos on YouTube for your query.",
"Sir, I'm initiating a YouTube search to provide information on your query.",
"I'll look up your query on YouTube and present the results.",
"Sir, searching your specific inquiry on YouTube for relevant videos.",
]
s1 = [
"Sir, now initiating the search for your inquiry.",
"I'm currently searching for information based on your query.",
"Let me find the relevant details for your inquiry.",
"Sir, I'm now conducting the search for the information you requested.",
"The search is underway for your specified inquiry.",
"Sir, I've begun the search process for your inquiry.",
"Let me fetch the information by conducting a search.",
"I'm in the process of searching for details based on your request.",
"Initiating the search now to provide you with the information.",
"Sir, the search is in progress for the details you're looking for.",

]
s2 = [
"The results should now be visible on your screen.",
"Sir, you should see the results displayed on your screen shortly.",
"The results are expected to appear on your screen.",
"Sir, the information you requested should now be visible on your screen.",
"Please check your screen for the results you asked for.",
"Sir, the relevant results should be visible on your screen.",
"The information you sought should now be on your screen.",
"Sir, you can expect to see the results on your screen shortly.",
"Check your screen for the requested results.",
"Sir, the results should now be displayed on your screen.",
]
playsong = [
"As you wish, sir. Playing your favorite music on YouTube now.",
"I'm queuing up some great tunes for you on YouTube.",
"Music is on its way. What genre are you in the mood for?",
"Let the music play on YouTube.",
"Get ready for a musical experience on YouTube.",
"Your command is my pleasure, sir. Initiating music playback on YouTube.",
"Your YouTube playlist is ready to roll.",
"At your service, sir! Let the music flow on YouTube.",
"Sit back and enjoy the music on YouTube.",
"Your wish is my command, sir. YouTube is now your personal DJ.",
]
q = [
"What genre or artist are you in the mood for today?",
" Any specific song or genre you have in mind for me to play?",
"Ready to play your favorite song. What shall it be?",
"Your wish is my command, sir! What song would you like me to play for you?",
"As your virtual assistant, sir, I'm here to play your preferred music. Any requests?",
"The musical stage is yours. What song would you like to hear?",
"sir Anubhav Chaturvedi! Any particular song on your mind right now?",
"At your service, sir! Feel free to let me know which song you'd like to play.",
"Ready to play the perfect song for you. Any specific choice?",
"Your playlist is in your hands, sir! What song shall I play for you?",
]

playing_dlg = [
"Engaged.",
"Affirmative.",
"Proceeding.",
"Confirmed.",
"Understood.",
"Executing.",
"Acknowledged.",
"Accepted.",
"Approved.",
"Authorizing.",
"Granted.",
"Advancing.",
"Implemented.",
"Complying.",
"Authoritative.",
"Activated.",
"Validated.",
"Sanctioned.",
"Verified.",
"Endorsed.",
]

x = [
    "play music in youtube",
    "play song on youtube",
    "Friday play music",
    "play some music",
    "gana bajao",
    "Friday play music",
    "Friday sing song",
    "Friday sing",
    "Friday music bajao",
    "Friday gana bajao yaar",
    "gana bajao",
    "music play karo",
    "play some good song",
    "sing song"
]
x1 = [
    "stop music",
    "with music band",
    "gana band karo",
    "music roko",
    "Friday stop music"

]
x2 = [
    "play again",
    "play",
    "start karo"
]